version: 2
updates:
- package-ecosystem: npm
  directory: "/rns-dev"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Europe/Prague
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@truffle/hdwallet-provider"
    versions:
    - 1.2.6
    - 1.3.0
  - dependency-name: truffle
    versions:
    - 5.1.63
    - 5.1.64
    - 5.1.65
    - 5.1.66
    - 5.1.67
    - 5.2.1
    - 5.2.2
    - 5.2.3
    - 5.2.4
    - 5.2.5
    - 5.3.2
